### ISSUE TITLE
Insufficient permissions to save files

### ISSUE THREAD

**Issue by kdwk** [phase1geo/Annotator#17]
This Flatpak does not have enough permissions to save annotated images. Permission to the home directory, or a portal, should be used

**Comment by saroele** [comment]
I suppose I have a similar issue. 
- installed Annotator as flatpak on linux Mint 20.2
- when exporting an annotated image, a file is saved but not with the chosen filename or extension. 

For example, I get a file like this `.xdp_test.2FOGF1` instead of a jpg. When I rename this file to `test.jpg` I can open it just fine and it contains the annotations.

**Comment by phase1geo** [comment]
In the master branch (and in the next stable release), the Flatpak manifest has been modified to open Home permissions by default, so that additional Flatpak permissions will not need to be changed to get basic application functionality.
