### ISSUE TITLE
Crashes with segfault - Settings.vala not found

### ISSUE THREAD

**Issue by adnan360** [phase1geo/Annotator#37]
I'm [trying to prepare a port](https://notabug.org/adnan360/openbsd-ports/src/master/graphics/annotator) for Annotator on OpenBSD 7.0. When run, it gives me:

```
$ com.github.phase1geo.annotator

** (com.github.phase1geo.annotator:27223): CRITICAL **: 01:52:17.277: Settings.vala:87: Could not connect: No such file or directory

** (com.github.phase1geo.annotator:27223): CRITICAL **: 01:52:17.277: Settings.vala:107: Could not connect: No such file or directory
Segmentation fault
```

Tried master too. Gives me the same error.

**Comment by phase1geo** [comment]
I apologize.  Somehow I missed this issue being reported.  Is this still a known issue?  The settings in question here are the GLib.settings (gsettings).  Not sure why these settings are causing an issue although I am neither an expert on OpenBSD nor GSettings.  I don't think this is due to any coding within Annotator (this is a global library where the error is being reported).
