### ISSUE TITLE
Publish to flathub

### ISSUE THREAD

**Issue by archisman-panigrahi** [phase1geo/Annotator#43]
Could you publish the app to flathub? Then it would be readily available in a whole lot of distros.

**Comment by apandada1** [comment]
Here are the app requirements: https://github.com/flathub/flathub/wiki/App-Requirements

And here's how to submit to flathub: https://github.com/flathub/flathub/wiki/App-Submission

Once published, GitHub actions automatically build from every commit, and pushes the released version to flathub. I would suggest to publish to flathub because then a lot of people would be able to easily install the app (I don't have any statistics, but compared to Mint or Ubuntu or Debian, the number of people who use Elementary OS is quite few).

-----------

Alternatively, if you don't want to publish to flathub, that's fine. After I opened this issue, [someone](https://askubuntu.com/questions/1386288/how-to-install-annotator-from-elementary-os-appcenter-in-ubuntu/1386289#comment2393025_1386289) found a way to install Annotator with flatpak on any distro, **without** building from source.

```
flatpak install https://flatpak.elementary.io/repo/appstream/com.github.phase1geo.annotator.flatpakref
```

In case you don't want to submit to flathub, please add this command to the README. Maybe rename the existing flatpak [section](https://github.com/phase1geo/Annotator#flatpak) to `Flatpak (build from source)`, and add this command to the Flatpak section. _Let me know if you want me to do that edit and submit a pull request._

**Comment by phase1geo** [comment]
I believe that Annotator is available on Flathub at present.  Closing this issue.
