### ISSUE TITLE
Center sequence numbers in circle

### ISSUE THREAD

**Issue by z0rb** [phase1geo/Annotator#87]
Hi,

thank you for the nice and simple tool for annotating images.

One small thing that would make sequence numbers better is centering. The numbers are all a bit to the right:
![image](https://github.com/phase1geo/Annotator/assets/3104604/14ac941c-fc52-487d-8f5f-690317f090c0)

I wonder if this might also be up to the font. Might be that they are actually centered, but the center of the number is not "optically" the center.

I have installed the Annotator on Debian Testing (Trixie) with Gnome. Found the install command here: https://github.com/phase1geo/Annotator/issues/43#issuecomment-1011803352
Maybe it influences the centering ...

**Comment by phase1geo** [comment]
I'm not exactly sure what is going on here.  When I draw the number, I get the text extents (i.e., width and height) from Cairo for the given number so that I can center the text.  So the code that is required to center the text is already there, but the text is still not being centered precisely as desired.  I can spend some time looking into this issue, but it's a lower priority issue at the moment.

**Comment by prokoudine** [comment]
My experience is slightly different. 1 is always off, starting with 2 it gets better.

![image](https://github.com/user-attachments/assets/bd6a8db5-e327-4b0f-a4f0-fd60383ec962)
